CREATE  VIEW  `portal`.`privilegi` AS select `utenti`.`id` AS `id_user`,`utenti`.`username` AS `username`,`utenti`.`nome` AS `nome`,`utenti`.`cognome` AS `cognome`,`diritti`.`diritto` AS `diritto`,`ruoliapplicativi`.`id` AS `id_ruoloapp`,`ruoliapplicativi`.`ruolo` AS `ruolo`,`applicazioni`.`applicazione` AS `applicazione` from ((((`ruoliapplicativi` join `applicazioni` on((`ruoliapplicativi`.`id_applicazione` = `applicazioni`.`id`))) join `diritti_ruoliapplicativi` on((`diritti_ruoliapplicativi`.`id_ruoloapp` = `ruoliapplicativi`.`id`))) join `diritti` on((`diritti_ruoliapplicativi`.`id_diritto` = `diritti`.`id`))) join `utenti` on((`diritti`.`id_user` = `utenti`.`id`)));

CREATE  VIEW  `portal`.`riepilogocapitoli` AS select `capitoli`.`voce` AS `voce`,`utenti`.`nome` AS `nome`,`utenti`.`cognome` AS `cognome`,`missioni`.`oggetto` AS `oggetto`,`missioni`.`costo` AS `costo` from ((`utenti` join `capitoli` on((`utenti`.`id_cap` = `capitoli`.`id`))) join `missioni` on((`missioni`.`id_ute` = `utenti`.`id`))) where (`missioni`.`stato` = 2) group by `capitoli`.`voce`,`utenti`.`nome`,`missioni`.`oggetto`;

CREATE  VIEW  `portal`.`riepilogomissdip` AS select `utenti`.`nome` AS `nome`,`utenti`.`cognome` AS `cognome`,`qualifica`.`qualifica` AS `qualifica`,`missioni`.`oggetto` AS `oggetto`,`missioni`.`costo` AS `costo` from ((`missioni` join `utenti` on((`missioni`.`id_ute` = `utenti`.`id`))) join `qualifica` on((`qualifica`.`id` = `utenti`.`id_qua`))) where (`missioni`.`stato` = 2);

DROP `portal`.`spese_tipi`;
CREATE  VIEW  `portal`.`spese_tipi` AS select `missioni`.`id` AS `id_trasferta`,`spese`.`id_tipo` AS `id_area`,`tipispese`.`tipo` AS `area`,`tipispese`.`tipo` AS `tipo`,`spese`.`descrizione` AS `descrizione`,`spese`.`qta` AS `qta`,`spese`.`cu` AS `cu` from ((`missioni` join `spese` on((`spese`.`id_trasferta` = `missioni`.`id`))) join `tipispese` on((`spese`.`id_tipo` = `tipispese`.`id`))) order by `missioni`.`id`,`spese`.`id_tipo`;

CREATE   VIEW  `portal`.`titolariperappuntamento` AS select `agenda`.`id` AS `id`,`agendatitolari`.`id_titolare` AS `id_titolare`,`agenda`.`data` AS `data`,concat(`agenda`.`ora`,' ',`agenda`.`ora_fraz`) AS `ora`,concat(`utenti`.`nome`,'-',`utenti`.`cognome`) AS `titolare`,`an_contatti`.`email` AS `email` from (((`agendatitolari` join `agenda` on((`agendatitolari`.`id_agenda` = `agenda`.`id`))) join `utenti` on((`agendatitolari`.`id_titolare` = `utenti`.`id`))) join `an_contatti` on((`agendatitolari`.`id_titolare` = `an_contatti`.`id_utente`)));

CREATE  VIEW  `portal`.`vaccessi` AS select `utenti`.`nome` AS `nome`,`utenti`.`cognome` AS `cognome`,`utenti`.`username` AS `username`,cast(`log`.`dataini` as date) AS `dataini`,cast(`log`.`datafin` as date) AS `datafin`,`log`.`tempoconn` AS `secondi`,truncate((`log`.`tempoconn` / 60),0) AS `minuti`,truncate((`log`.`tempoconn` / 3600),0) AS `ore` from (`log` join `utenti` on((`log`.`id_utente` = `utenti`.`id`))) where (cast(`log`.`datafin` as date) <> str_to_date('01/01/1900','%d/%m/%Y'));

CREATE   VIEW  `portal`.`vagenda` AS select `agenda`.`id` AS `id_appuntamento`,`an_contatti`.`id` AS `id_richiedente`,concat(`an_contatti`.`cognome`,`an_contatti`.`nome`) AS `richiedente`,`an_contatti`.`ragsoc` AS `ragsocrich`,`agenda`.`tipo` AS `tipo`,`agenda`.`titolo` AS `oggetto`,`agenda`.`descrizione` AS `descrizione`,`utenti`.`id` AS `id_titolare`,concat(`utenti`.`nome`,'-',`utenti`.`cognome`) AS `titolari`,`agenda`.`data` AS `data`,`agenda`.`ora` AS `ora`,`agenda`.`ora_fraz` AS `min`,concat(`agenda`.`ora`,':',`agenda`.`ora_fraz`) AS `oramin`,`agenda`.`stato` AS `stato` from (((`agendatitolari` join `utenti`) join `agenda`) join `an_contatti`) where ((`agendatitolari`.`id_titolare` = `utenti`.`id`) and (`agendatitolari`.`id_agenda` = `agenda`.`id`) and (`agenda`.`id_richiedente` = `an_contatti`.`id`)) group by `agenda`.`id`,`agenda`.`id_richiedente`,`agenda`.`tipo`,`agenda`.`titolo`,`agenda`.`descrizione`,`agendatitolari`.`id_titolare`,`agenda`.`data`,concat(`agenda`.`ora`,':',`agenda`.`ora_fraz`),`agenda`.`stato` order by `agenda`.`data` desc,`agenda`.`ora`,`agenda`.`ora_fraz`;

CREATE   VIEW  `portal`.`vcontatti` AS select `an_contatti`.`id` AS `id`,`an_contatti`.`nome` AS `nome`,`an_contatti`.`cognome` AS `cognome`,`an_contatti`.`ragsoc` AS `ragsoc`,`an_contatti`.`tel` AS `tel`,`an_contatti`.`sito` AS `sito`,`an_contatti`.`email` AS `email`,`an_contatti`.`emailsec` AS `emailsec`,`an_contatti`.`cell1` AS `cell1`,`an_contatti`.`cell2` AS `cell2`,`an_contatti`.`note` AS `note`,`an_contatti`.`stato` AS `stato` from `an_contatti` where (`an_contatti`.`tipo` = 'EST');

DROP `portal`.`vdelegatiapp`;
CREATE   VIEW  `portal`.`vdelegatiapp` AS select `agenda`.`id` AS `id_appuntamento`,`agenda`.`tipo` AS `tipo`,`delegatititolari`.`id_delegato` AS `id_delegato`,`delegatititolari`.`nomedel` AS `delegato`,`agendatitolari`.`id_titolare` AS `id_titolare`,`utenti`.`nome` AS `titolare`,`agenda`.`data` AS `data`,`agenda`.`ora` AS `ora`,`agenda`.`ora_fraz` AS `ora_fraz` from (((`agendatitolari` join `utenti` on((`agendatitolari`.`id_titolare` = `utenti`.`id`))) join `agenda` on((`agendatitolari`.`id_agenda` = `agenda`.`id`))) left join `delegatititolari` on((`agendatitolari`.`id_titolare` = `delegatititolari`.`id_titolare`)));

CREATE  VIEW  `portal`.`vgiornale` AS select `log_registro`.`id` AS `id`,`log_registro`.`id_registro` AS `id_registro`,`tipi_atti`.`descrizione` AS `tipoatto`,`enti`.`nome` AS `ente`,`log_registro`.`oggetto` AS `oggetto`,concat(`ut1`.`nome`,`ut1`.`cognome`) AS `creatore`,concat(`ut2`.`nome`,`ut2`.`cognome`) AS `modificatore`,`log_registro`.`dal` AS `dal`,`log_registro`.`al` AS `al`,`log_registro`.`datamod` AS `datamod`,`log_registro`.`datareg` AS `datareg`,`log_registro`.`periodo` AS `periodo`,`log_registro`.`stato` AS `stato`,`log_registro`.`codice` AS `codice`,`log_registro`.`anno` AS `anno`,`log_registro`.`progr` AS `progr` from (((((`log_registro` join `tipi_atti` on((`log_registro`.`id_tipo` = `tipi_atti`.`id`))) join `enti` on((`log_registro`.`id_ente` = `enti`.`id`))) join `utenti` `ut1` on((`log_registro`.`id_utente` = `ut1`.`id`))) join `registro` on((`log_registro`.`id_registro` = `registro`.`id`))) join `utenti` `ut2` on((`log_registro`.`id_utente_mod` = `ut2`.`id`))) group by `log_registro`.`id_registro`,`log_registro`.`id`;

CREATE   VIEW  `portal`.`vmessaggi` AS select `a`.`id` AS `id`,`a`.`id_rif` AS `rif`,`a`.`data_crea` AS `data`,`a`.`oggetto` AS `oggetto`,`a`.`testo` AS `testo`,`a`.`id_mitt` AS `id_mitt`,concat(`b`.`cognome`,' ',`b`.`nome`) AS `mittente`,`a`.`id_dest` AS `id_dest`,concat(`c`.`cognome`,' ',`c`.`nome`) AS `destinatario`,`a`.`stato` AS `stato` from ((`messaggi` `a` join `utenti` `b`) join `utenti` `c`) where ((`a`.`id_mitt` = `b`.`id`) and (`a`.`id_dest` = `c`.`id`)) order by `a`.`data_crea` desc;

DROP `portal`.`vmissioni`;
CREATE   VIEW  `portal`.`vmissioni` AS select `missioni`.`id` AS `id`,`missioni`.`stato` AS `stato`,`utenti`.`id` AS `id_ute`,`utenti`.`cognome` AS `cognome`,`utenti`.`nome` AS `nome`,`missioni`.`oggetto` AS `oggetto`,`capitoli`.`voce` AS `capitolo`,`missioni`.`citta` AS `citta`,`missioni`.`data_p` AS `data_p`,`missioni`.`data_r` AS `data_r`,`missioni`.`ore_miss` AS `ore_miss`,`missioni`.`costo` AS `costo` from ((`missioni` join `capitoli`) join `utenti`) where ((`missioni`.`capitolo` = `capitoli`.`voce`) and (`missioni`.`id_ute` = `utenti`.`id`)) order by `utenti`.`cognome`;

CREATE   VIEW  `portal`.`vordinanze` AS select `ordinanze`.`id` AS `id`,`ordinanze`.`codice` AS `codice`,`ordinanze`.`rif` AS `rif`,`ordinanti`.`cognome` AS `ordinante`,concat(`utenti`.`nome`,' ',`utenti`.`cognome`) AS `gestore`,`tipi_ordinanze`.`descrizione` AS `tipo`,`ordinanze`.`oggetto` AS `oggetto`,`ordinanze`.`descrizione` AS `descrizione`,`ordinanze`.`file` AS `file`,`ordinanze`.`stato` AS `stato` from (((`ordinanze` join `utenti`) join `ordinanti`) join `tipi_ordinanze`) where ((`ordinanze`.`id_ordinante` = `ordinanti`.`id`) and (`ordinanze`.`id_tipo` = `tipi_ordinanze`.`id`) and (`ordinanze`.`id_utente` = `utenti`.`id`)) order by `ordinanze`.`anno` desc,`ordinanze`.`progr` desc;

CREATE  VIEW  `portal`.`vregistro` AS select `registro`.`id` AS `id`,`enti`.`nome` AS `ente`,`registro`.`id_tipo` AS `id_tipo`,`tipi_atti`.`descrizione` AS `tipo`,`registro`.`oggetto` AS `oggetto`,`registro`.`descrizione` AS `descrizione`,`registro`.`id_utente` AS `id_utente`,concat(`utenti`.`nome`,'  ',`utenti`.`cognome`) AS `responsabile`,date_format(`registro`.`dal`,'%d-%m-%Y') AS `dal`,date_format(`registro`.`al`,'%d-%m-%Y') AS `al`,`registro`.`datamod` AS `datamod`,`registro`.`datareg` AS `datareg`,`registro`.`periodo` AS `periodo`,`registro`.`stato` AS `stato`,`registro`.`codice` AS `codice`,`registro`.`anno` AS `anno`,`registro`.`progr` AS `progr`,`registro`.`rif` AS `rif`,`tipi_atti`.`descrizione` AS `tipoatto` from (((`registro` join `tipi_atti` on((`registro`.`id_tipo` = `tipi_atti`.`id`))) join `enti` on((`registro`.`id_ente` = `enti`.`id`))) join `utenti` on((`registro`.`id_utente` = `utenti`.`id`))) order by `registro`.`anno` desc,`registro`.`progr` desc;



DROP `portal`.`vtitolari`;
CREATE   VIEW  `portal`.`vtitolari` AS select `privilegi`.`id_user` AS `id_user`,concat(`privilegi`.`nome`,'.".\'-\'.".',`privilegi`.`cognome`) AS `titolare` from `privilegi` where (`privilegi`.`applicazione` = 'Agenda');
